Name:           ros-lunar-rosconsole-bridge
Version:        0.5.1
Release:        0%{?dist}
Summary:        ROS rosconsole_bridge package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rosconsole_bridge
Source0:        %{name}-%{version}.tar.gz

Requires:       console-bridge-devel
Requires:       ros-lunar-rosconsole
BuildRequires:  console-bridge-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-rosconsole >= 1.11.5

%description
rosconsole_bridge is a package used in conjunction with console_bridge and
rosconsole for connecting console_bridge-based logging to rosconsole-based
logging.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Mon Feb 05 2018 Dirk Thomas <dthomas@osrfoundation.org> - 0.5.1-0
- Autogenerated by Bloom

* Wed Oct 25 2017 Dirk Thomas <dthomas@osrfoundation.org> - 0.5.0-0
- Autogenerated by Bloom

* Wed Feb 22 2017 Dirk Thomas <dthomas@osrfoundation.org> - 0.4.4-0
- Autogenerated by Bloom

